import sqlite3

def create_drive_table():
    conn = sqlite3.connect('Placement_Portal.db')
    cursor = conn.cursor()
    
    cursor.execute('''CREATE TABLE DRIVE(ID INTEGER PRIMARY KEY AUTOINCREMENT, COMPANY_ID INTEGER NOT NULL, TITLE VARCHAR NOT NULL,
                  DESCRIPTION VARCHAR NOT NULL, ELIGIBILITY_CRITERIA VARCHAR NOT NULL, APPLICATION_DEADLINE DATE NOT NULL, 
                  APPROVAL_STATUS VARCHAR NOT NULL DEFAULT 'PENDING', STATUS VARCHAR NOT NULL DEFAULT 'ACTIVATED', VACANCIES INTEGER NOT NULL, PLACED INTEGER NOT NULL, 
                  FOREIGN KEY(COMPANY_ID) REFERENCES COMPANY(ID))''')
    
    conn.commit()
    conn.close()